version: "3"

services:
  nginx:
    image: "nginx"
    volumes:
      - ./ssl:/home/point/ssl
      - ./www/maintenance:/srv
      - ./www/maintenance/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      #- 8080:80
      - 80:80
      - 443:443